fix: ci/cd workflow error
MSBuild version 17.8.32+74df0b3f5 for .NET
MSBUILD : error MSB1009: Project file does not exist.
Switch:
Error: Process completed with exit code 1.

Signed-off-by: Dominik Viererbe <dominik.viererbe@canonical.com>