fix: dpkg-buildpackage can't find Time/Piece.pm
Due to snap confinement dpkg-buildpackage couldn't find the
Time/Piece.pm perl module:

```
dpkg-buildpackage: error: changelog format Debian is unknown: Can't locate Time/Piece.pm in @INC (you may need to install the Time::Piece module) (@INC entries checked: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.38.2 /usr/local/share/perl/5.38.2 /usr/lib/x86_64-linux-gnu/perl5/5.38 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.38 /usr/share/perl/5.38 /usr/local/lib/site_perl) at /usr/share/perl5/Dpkg/Changelog/Entry/Debian.pm line 44.
BEGIN failed--compilation aborted at /usr/share/perl5/Dpkg/Changelog/Entry/Debian.pm line 44.
Compilation failed in require at /usr/share/perl5/Dpkg/Changelog/Debian.pm line 53.
BEGIN failed--compilation aborted at /usr/share/perl5/Dpkg/Changelog/Debian.pm line 53.
Compilation failed in require at (eval 12) line 2.
```

This commit fixes this issue.

Signed-off-by: Dominik Viererbe <dominik.viererbe@canonical.com>